#!/usr/bin/env sh

sv status "${service_name}"
IS_ALREADY_RUNNING="$?"

set -e

service_path="/etc/sv/${service_name}"
mkdir -p "${service_path}"

service_run_path="${service_path}/run"
run_contents="#!/usr/bin/env sh
${command}"
echo "${run_contents}" > "${service_run_path}"
chmod +x "${service_run_path}"

ln -sfT "${service_path}" "/etc/service/${service_name}"

if [ "$IS_ALREADY_RUNNING" -eq 0 ]; then
    sv restart "${service_name}"
fi
