#!/usr/bin/env python

import argparse
import json
import time

import spur

import beach


def main():
    _commands = [DeployCommand(), RegisterCommand()]
    
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    
    for command in _commands:
        subparser = subparsers.add_parser(command.name)
        subparser.set_defaults(func=command.execute)
        command.create_parser(subparser)
    
    args = parser.parse_args()
    args.func(args)
    
    return parser.parse_args()


class DeployCommand(object):
    name = "deploy"
    
    def create_parser(self, parser):
        parser.add_argument("app_path", metavar="app-path")
        _add_config_arg(parser)
    
    def execute(self, args):
        app_path = args.app_path
        config = _read_config(args)
        
        with beach.supervisors.stop_on_exit() as supervisor:
            with beach.layouts.TemporaryLayout() as layout:
                deployer = beach.Deployer(
                    supervisor=supervisor,
                    layout=layout,
                    registry=None,
                )
        
                params = config["params"]
                
                deployer.deploy(app_path, params=params)
                
                try:
                    while True:
                        time.sleep(0.1)
                except KeyboardInterrupt:
                    return


class RegisterCommand(object):
    name = "register"
    
    def create_parser(self, parser):
        parser.add_argument("name")
        _add_config_arg(parser)
        parser.add_argument("--provide", "-p", action="append", default=[])
    
    def execute(self, args):
        registry = _read_registry_arg(args)
        
        provides = dict(
            provide.split("=", 1)
            for provide in args.provide
        )
        
        registry.register(args.name, provides)


def _read_registry_arg(args):
    config = _read_config(args)
    return beach.registries.FileRegistry(spur.LocalShell(), config["registry"]["file"])


def _read_config(args):
    config_path = args.config
    
    with open(config_path) as config_file:
        return json.load(config_file)


def _add_config_arg(parser):
    parser.add_argument("--config", "-c", required=True)
    


if __name__ == "__main__":
    main()
